"""
Django settings for rule_editor project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ

from platformshconfig import Config
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

from django.contrib import admin

from dotenv import load_dotenv

load_dotenv(override=True)

env = environ.Env(
    DEBUG=(bool, False),
    SECRET_KEY=(str, ""),
    SENTRY_DSN=(str, ""),
    NLP_API=(str, ""),
    NLP_API_USER=(str, None),
    NLP_API_PASSWORD=(str, None),
    PLATFORM_SMTP_HOST=(str, None),
    PLATFORM_SMTP_PORT=(int, 25),
    AZURE_OPENAI_ENDPOINT=(str, None),
    AZURE_OPENAI_KEY=(str, None),
    AZURE_OPENAI_VERSION=(str, None),
    AZURE_OPENAI_MODEL=(str, None),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

if env("SENTRY_DSN"):
    sentry_sdk.init(
        dsn=env("SENTRY_DSN"),
        release="1.2.21",
        send_default_pii=True,
        integrations=[
            DjangoIntegration(
                transaction_style="url",
                middleware_spans=True,
                signals_spans=False,
                cache_spans=False,
            ),
        ],
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        # We recommend adjusting this value in production,
        traces_sample_rate=1.0,
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = ["*"]

NLP_API = env("NLP_API")
NLP_API_USER = env("NLP_API_USER")
NLP_API_PASSWORD = env("NLP_API_PASSWORD")

AZURE_OPENAI_ENDPOINT = env("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_KEY = env("AZURE_OPENAI_KEY")
AZURE_OPENAI_VERSION = env("AZURE_OPENAI_VERSION")
AZURE_OPENAI_MODEL = env("AZURE_OPENAI_MODEL")

# Application definition

INSTALLED_APPS = [
    "rules",
    "dal",
    "dal_select2",
    "grappelli",
    "debug_toolbar",
    "import_export",
    "ordered_model",
    "rangefilter",
    "more_admin_filters",
    "taggit",
    "computedfields",
    "nested_admin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "rule_editor.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rule_editor.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "database/db.sqlite3"),
        "OPTIONS": {
            "timeout": 20,  # 5 seconds is the default, but we can increase it to, e.g., 20s
            "transaction_mode": "IMMEDIATE",  # <-- Set the transaction mode to IMMEDIATE
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = ()

STATIC_URL = "/static/"

STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INTERNAL_IPS = [
    "127.0.0.1",
]

# Email

EMAIL_HOST = env("PLATFORM_SMTP_HOST")
EMAIL_PORT = env("PLATFORM_SMTP_PORT")


def get_app_list(self, request, app_label=None):
    app_dict = self._build_app_dict(request, app_label)

    return list(app_dict.values())


admin.AdminSite.get_app_list = get_app_list

# Import some Platform.sh settings from the environment.
config = Config()
if config.is_valid_platform():
    if config.appDir:
        STATIC_ROOT = os.path.join(config.appDir, "static")
    if config.projectEntropy:
        SECRET_KEY = config.projectEntropy

GRAPPELLI_AUTOCOMPLETE_LIMIT = 10
GRAPPELLI_SWITCH_USER = False
