# Generated by Django 4.2.4 on 2023-09-04 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
import rules.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiversityDimension",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "source_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "language",
                    django_enum.fields.EnumCharField(
                        choices=[("en", "English"), ("de", "German")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("lemma", models.JSONField()),
                ("word_types", models.JSONField()),
                ("label", models.TextField(blank=True, null=True)),
                ("is_inspiration", models.BooleanField(default=False)),
                ("is_context_aware", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("url", models.TextField(blank=True, null=True)),
                ("reference", models.TextField(blank=True, null=True)),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrainingSentence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "source_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("is_false_positive", models.BooleanField(default=False)),
                ("is_training_data", models.BooleanField(default=False)),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rules.rule"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rules.source",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RuleDiversityDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "diversity_dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules.diversitydimension",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rules.rule"
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("rule", "diversity_dimension")},
            },
        ),
        migrations.AddField(
            model_name="rule",
            name="diversity_dimensions",
            field=models.ManyToManyField(
                through="rules.RuleDiversityDimension", to="rules.diversitydimension"
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="ownedby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rules.source",
            ),
        ),
        migrations.CreateModel(
            name="Alternative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "source_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "language",
                    django_enum.fields.EnumCharField(
                        choices=[("en", "English"), ("de", "German")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("lemma", models.JSONField()),
                ("word_types", models.JSONField()),
                ("is_singular", models.BooleanField(default=True)),
                ("is_inspiration", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("label", models.TextField(blank=True, null=True)),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rules.rule"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rules.source",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.AlterUniqueTogether(
            name="rule",
            unique_together={("language", "lemma")},
        ),
    ]
