# Generated by Django 4.2.4 on 2023-09-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0002_category_diversitydimension_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternative",
            name="lemma_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="alternative",
            name="word_types_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="rule",
            name="lemma_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="rule",
            name="word_types_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="lemma",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="word_types",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="rule",
            name="lemma",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="rule",
            name="word_types",
            field=models.CharField(max_length=255),
        ),
    ]
