# Generated by Django 4.2.4 on 2023-09-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0003_alternative_lemma_json_alternative_word_types_json_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alternative",
            name="language",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="is_inspiration",
        ),
        migrations.AlterField(
            model_name="alternative",
            name="id",
            field=models.AutoField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="id",
            field=models.AutoField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
