# Generated by Django 4.2.5 on 2023-09-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0004_remove_alternative_language_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="rulediversitydimension",
            name="is_advanced",
            field=models.BooleanField(default=False),
        ),
    ]
