# Generated by Django 4.2.5 on 2023-09-06 09:25

from django.db import migrations, models
import django.utils.timezone
import rules.models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0005_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="source",
            name="updated_at",
            field=rules.models.AutoDateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="rulediversitydimension",
            name="id",
            field=models.AutoField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
