# Generated by Django 4.2.5 on 2023-09-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0006_source_created_at_source_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rule",
            unique_together={("language", "lemma", "word_types", "lemma")},
        ),
        migrations.AddField(
            model_name="rule",
            name="is_prefix",
            field=models.BooleanField(default=False),
        ),
    ]
