# Generated by Django 4.2.5 on 2023-09-08 10:59

from django.db import migrations
import rules.models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0007_alter_rule_unique_together_rule_is_prefix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alternative",
            name="source_text",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="source_text",
        ),
        migrations.RemoveField(
            model_name="trainingsentence",
            name="source_text",
        ),
    ]
