# Generated by Django 4.2.5 on 2023-09-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0008_remove_alternative_source_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diversitydimension",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="diversitydimension",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
