# Generated by Django 4.2.5 on 2023-09-26 07:58

from django.db import migrations, models
import django_enum.fields
import rules.models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0010_falsepositive"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternative",
            name="type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("default", "Default"),
                    ("person_first", "Person First"),
                    ("identity_first", "Identity First"),
                ],
                default="default",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diversitydimension",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="falsepositive",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="reference",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingsentence",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
