# Generated by Django 4.2.5 on 2023-09-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0011_alternative_type_alter_alternative_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="falsepositive",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
