# Generated by Django 4.2.5 on 2023-09-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0012_alter_falsepositive_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="is_marked_for_review",
            field=models.BooleanField(default=False),
        ),
    ]
