# Generated by Django 4.2.5 on 2023-09-26 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0013_rule_is_marked_for_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rulediversitydimension",
            name="is_advanced",
        ),
    ]
