# Generated by Django 4.2.5 on 2023-09-29 09:00

from django.db import migrations, models
import rules.models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0014_remove_rulediversitydimension_is_advanced"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="emoji",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="explanation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
