# Generated by Django 4.2.5 on 2023-09-29 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rules.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rules", "0015_rule_emoji_rule_explanation_rule_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="falsepositive",
            old_name="name",
            new_name="false_positive",
        ),
        migrations.CreateModel(
            name="Lemmatization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("text", models.CharField(max_length=255, unique=True)),
                ("lemma", models.CharField(max_length=255, unique=True)),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
