# Generated by Django 4.2.5 on 2023-09-29 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
import rules.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rules", "0016_rename_name_falsepositive_false_positive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lemmatization",
            name="language",
            field=django_enum.fields.EnumCharField(
                choices=[("en", "English"), ("de", "German")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="lemmatization",
            name="lemma",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lemmatization",
            name="text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="lemmatization",
            unique_together={("language", "text")},
        ),
        migrations.AlterUniqueTogether(
            name="rule",
            unique_together={("language", "lemma", "word_types")},
        ),
        migrations.CreateModel(
            name="Verb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("comment", rules.models.HideTextField(blank=True, null=True)),
                ("base_form", models.CharField(max_length=255, unique=True)),
                (
                    "language",
                    django_enum.fields.EnumCharField(
                        choices=[("en", "English"), ("de", "German")],
                        default="de",
                        max_length=2,
                    ),
                ),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("language", "base_form")},
            },
        ),
        migrations.CreateModel(
            name="Noun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("comment", rules.models.HideTextField(blank=True, null=True)),
                ("base_form", models.CharField(max_length=255, unique=True)),
                (
                    "language",
                    django_enum.fields.EnumCharField(
                        choices=[("en", "English"), ("de", "German")],
                        default="de",
                        max_length=2,
                    ),
                ),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("language", "base_form")},
            },
        ),
        migrations.CreateModel(
            name="Adjective",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("comment", rules.models.HideTextField(blank=True, null=True)),
                ("base_form", models.CharField(max_length=255, unique=True)),
                (
                    "language",
                    django_enum.fields.EnumCharField(
                        choices=[("en", "English"), ("de", "German")],
                        default="de",
                        max_length=2,
                    ),
                ),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("language", "base_form")},
            },
        ),
    ]
