# Generated by Django 4.2.5 on 2023-10-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0017_lemmatization_language_alter_lemmatization_lemma_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternative",
            name="is_advanced",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="diversitydimension",
            name="is_advanced",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="diversitydimension",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rules.diversitydimension",
            ),
        ),
    ]
