# Generated by Django 4.2.5 on 2023-10-01 12:10

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0018_alternative_is_advanced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("default", "Default"),
                    ("hr", "Hr"),
                    ("marketing", "Marketing"),
                    ("legal", "Legal"),
                ],
                default="default",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="is_context_aware",
            field=models.BooleanField(
                default=False,
                help_text="Uses custom machine learning model to determine if to highlight in the given context.",
            ),
        ),
    ]
