# Generated by Django 4.2.5 on 2023-10-02 11:36

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("rules", "0019_rule_type_alter_rule_is_context_aware"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="type",
        ),
        migrations.AddField(
            model_name="alternative",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="text_id",
            field=models.CharField(
                default="",
                help_text="String used to identify the rule, f.e. in the top words of the analytics",
                max_length=255,
                null=False,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="trainingsentence",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="is_prefix",
            field=models.BooleanField(
                default=False,
                help_text="Rule checks the prefix of the lemma (only one token allowed).",
            ),
        ),
    ]
