# Generated by Django 4.2.5 on 2023-10-02 15:46

from django.db import migrations, models
import django_enum.fields
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("rules", "0020_remove_rule_type_alternative_tags_rule_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alternative",
            name="is_singular",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="is_prefix",
        ),
        migrations.AddField(
            model_name="alternative",
            name="pluralization",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("default", "Default"),
                    ("singular_only", "Singular Only"),
                    ("plural_only", "Plural Only"),
                ],
                default="default",
                max_length=13,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("default", "Default"),
                    ("prefix", "Prefix"),
                    ("suffix", "Suffix"),
                    ("substring", "Substring"),
                ],
                default="default",
                help_text="Should the rule check on part of the lemma (only 'default' allows multiple token lemma).",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="text_id",
            field=models.CharField(
                help_text="String used to identify the rule, f.e. in the top words of the analytics",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsentence",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
