# Generated by Django 4.2.5 on 2023-10-03 11:22

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0021_remove_alternative_is_singular_remove_rule_is_prefix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="label_type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("default", "Default"),
                    ("not_for_people", "Not For People"),
                    ("be_specific", "Be Specific"),
                    ("name_disability", "Name Disability"),
                    (
                        "only_if_gender_identity_relevant",
                        "Only If Gender Identity Relevant",
                    ),
                    ("not_for_non_combat", "Not For Non Combat"),
                ],
                default="default",
                help_text="Quick selections for custom labels (only change from 'default' if label is empty).",
                max_length=32,
            ),
        ),
    ]
