# Generated by Django 4.2.5 on 2023-10-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0022_rule_label_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternative",
            name="lemma_json",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="word_types_json",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name="rule",
            name="lemma_json",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name="rule",
            name="word_types_json",
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
