# Generated by Django 4.2.5 on 2023-10-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0023_alter_alternative_lemma_json_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diversitydimension",
            name="parent",
        ),
        migrations.AddField(
            model_name="diversitydimension",
            name="parent_name",
            field=models.CharField(default="parent", max_length=255),
            preserve_default=False,
        ),
    ]
