# Generated by Django 4.2.5 on 2023-10-04 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0024_remove_diversitydimension_parent_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="diversitydimension",
            unique_together={("parent_name", "is_advanced")},
        ),
    ]
