# Generated by Django 4.2.5 on 2023-10-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0025_alter_diversitydimension_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="first_is_word_type_lemmatize",
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="first_is_word_type_lower_case",
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="first_token",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="first_word_type",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="word_types",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="word_types",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
