# Generated by Django 4.2.5 on 2023-10-08 14:18

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0026_rule_first_is_word_type_lemmatize_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="label_type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("default", "Default"),
                    ("not_for_people", "Not For People"),
                    ("be_specific", "Be Specific"),
                    ("name_disability", "Name Disability"),
                    (
                        "only_if_gender_identity_relevant",
                        "Only If Gender Identity Relevant",
                    ),
                    ("not_for_non_combat", "Not For Non Combat"),
                    ("ask_for_preference", "Ask For Preference"),
                    ("ask_about_traditions", "Ask About Traditions"),
                    (
                        "only_when_referencing_religious_practice",
                        "Only When Referencing Religious Practice",
                    ),
                    ("dont_use_for_substance_use", "Dont Use For Substance Use"),
                    ("dont_use_to_describe_quality", "Dont Use To Describe Quality"),
                    ("use_in_tech_only", "Use In Tech Only"),
                ],
                default="default",
                help_text="Quick selections for custom labels (only change from 'default' if label is empty).",
                max_length=40,
            ),
        ),
    ]
