# Generated by Django 4.2.5 on 2023-10-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0027_alter_rule_label_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="falsepositive",
            name="false_positive",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="falsepositive",
            unique_together={("rule", "false_positive")},
        ),
    ]
