# Generated by Django 4.2.5 on 2023-10-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0028_alter_falsepositive_false_positive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternative",
            name="is_placeholder",
            field=models.BooleanField(default=True),
        ),
    ]
