# Generated by Django 4.2.5 on 2023-10-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0029_alternative_is_placeholder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternative",
            name="is_placeholder",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
