# Generated by Django 4.2.5 on 2023-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0030_alter_alternative_is_placeholder"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=[
                    "first_token",
                    "first_is_word_type_lemmatize",
                    "first_is_word_type_lower_case",
                    "first_word_type",
                ],
                name="rules_rule_first_t_9fb687_idx",
            ),
        ),
    ]
