# Generated by Django 4.2.6 on 2023-10-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0031_rule_rules_rule_first_t_9fb687_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="diversity_dimension_json",
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
