# Generated by Django 4.2.6 on 2023-10-10 12:34

from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0032_rule_diversity_dimension_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternative",
            name="is_remove",
            field=models.BooleanField(
                default=False,
                help_text="User will be offered to remove the words instead of a text alternative",
            ),
        ),
        migrations.AlterField(
            model_name="adjective",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Any useful comments to keep for internal purposes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Any useful comments to keep for internal purposes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="is_advanced",
            field=models.BooleanField(
                default=True,
                help_text="Only show if user has diversity dimension enabled at advanced level.",
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="is_inspiration",
            field=models.BooleanField(
                default=False,
                help_text="Alternative will be marked as inspiration, hidden if user has inspiration disabled. Also never adjusted for grammatical correctness",
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Additional label to add to the short explanation/alternative",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="lemma",
            field=models.CharField(
                help_text="Lemma is one or multiple words (tokens) either in lemmatized form or not (depending on the word_types)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="pluralization",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("default", "Default"),
                    ("singular_only", "Singular Only"),
                    ("plural_only", "Plural Only"),
                ],
                default="default",
                help_text="Show alternative in case rule triggered on",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternatives",
                to="rules.rule",
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="word_types",
            field=models.CharField(
                blank=True,
                help_text="'|' separated list of word types (s, a, adv, v, conj, emoji) and optional modifiers: '=' case sensitive unlemmatized, '~' case insensitive unlemmatize, '-' case sensitive lemmatized",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Any useful comments to keep for internal purposes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Machine name of the category", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="diversitydimension",
            name="category",
            field=models.ForeignKey(
                help_text="Top-level category",
                on_delete=django.db.models.deletion.CASCADE,
                to="rules.category",
            ),
        ),
        migrations.AlterField(
            model_name="diversitydimension",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Any useful comments to keep for internal purposes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="diversitydimension",
            name="is_advanced",
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="diversitydimension",
            name="name",
            field=models.CharField(
                help_text="Machine name of the diversity dimension (with optional '_advanced' suffix)",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="diversitydimension",
            name="parent_name",
            field=models.CharField(
                help_text="Machine name of the diversity dimension (without optional '_advanced' suffix)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="falsepositive",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Any useful comments to keep for internal purposes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="falsepositive",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="false_positives",
                to="rules.rule",
            ),
        ),
        migrations.AlterField(
            model_name="lemmatization",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Any useful comments to keep for internal purposes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lemmatization",
            name="lemma",
            field=models.CharField(
                help_text="Lemma used for the given source text", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="lemmatization",
            name="text",
            field=models.CharField(help_text="Source text", max_length=255),
        ),
        migrations.AlterField(
            model_name="noun",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Any useful comments to keep for internal purposes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Any useful comments to keep for internal purposes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="emoji",
            field=models.CharField(
                blank=True,
                help_text="Override the diversity dimension emoji with a custom emoji",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="explanation",
            field=models.CharField(
                blank=True,
                help_text="Override the diversity dimension text with a custom explanation",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="is_marked_for_review",
            field=models.BooleanField(
                default=False, help_text="Rule should be reviewed"
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Additional label to add to the short explanation/alternative",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="lemma",
            field=models.CharField(
                help_text="Lemma is one or multiple words (tokens) either in lemmatized form or not (depending on the word_types)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="Override the diversity dimension URL with a custom URL",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="word_types",
            field=models.CharField(
                blank=True,
                help_text="'|' separated list of word types (s, a, adv, v, conj, emoji) and optional modifiers: '=' case sensitive unlemmatized, '~' case insensitive unlemmatize, '-' case sensitive lemmatized",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(
                help_text="Some short text identifier for the source",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="reference",
            field=models.TextField(
                blank=True,
                help_text="A reference to a non URL source, f.e. ISBN, journal name/number etc.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.CharField(
                blank=True, help_text="URL to the source", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trainingsentence",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Any useful comments to keep for internal purposes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trainingsentence",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_sentences",
                to="rules.rule",
            ),
        ),
        migrations.AlterField(
            model_name="verb",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Any useful comments to keep for internal purposes.",
                null=True,
            ),
        ),
    ]
