# Generated by Django 4.2.6 on 2023-10-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0033_alternative_is_remove_alter_adjective_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Any useful comments to keep for internal purposes.",
                null=True,
            ),
        ),
    ]
