# Generated by Django 4.2.6 on 2023-10-10 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rules.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rules", "0034_source_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnglishAdjective",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Any useful comments to keep for internal purposes.",
                        null=True,
                    ),
                ),
                ("base_form", models.CharField(max_length=255, unique=True)),
                (
                    "comparative",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "superlative",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnglishNoun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Any useful comments to keep for internal purposes.",
                        null=True,
                    ),
                ),
                ("base_form", models.CharField(max_length=255, unique=True)),
                ("plural", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnglishVerb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Any useful comments to keep for internal purposes.",
                        null=True,
                    ),
                ),
                ("base_form", models.CharField(max_length=255, unique=True)),
                ("past_tense", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "past_participle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "present_participle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "third_person_singular",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Adjective",
        ),
        migrations.DeleteModel(
            name="Noun",
        ),
        migrations.DeleteModel(
            name="Verb",
        ),
    ]
