# Generated by Django 4.2.6 on 2023-10-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0035_englishadjective_englishnoun_englishverb_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternative",
            name="order",
            field=models.PositiveIntegerField(db_index=True, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="englishadjective",
            name="base_form",
            field=models.CharField(
                help_text="ie. absolute", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="englishnoun",
            name="base_form",
            field=models.CharField(
                help_text="ie. singular", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="rulediversitydimension",
            name="order",
            field=models.PositiveIntegerField(db_index=True, verbose_name="order"),
        ),
    ]
