# Generated by Django 4.2.6 on 2023-10-11 18:33

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0036_alter_alternative_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternative",
            name="language",
            field=django_enum.fields.EnumCharField(
                choices=[("en", "English"), ("de", "German")],
                default="en",
                editable=False,
                max_length=2,
            ),
        ),
    ]
