# Generated by Django 4.2.6 on 2023-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0037_alternative_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="diversitydimension",
            name="proficiency_level",
            field=models.CharField(
                default="",
                help_text="Proficiency level of the diversity dimension ('inclusive', 'unconscious_bias', 'openly_discriminating', ..)",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
