# Generated by Django 4.2.6 on 2023-10-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0038_diversitydimension_proficiency_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="has_training_sentences",
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
    ]
