# Generated by Django 4.2.6 on 2023-11-01 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rules.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rules", "0039_rule_has_training_sentences"),
    ]

    operations = [
        migrations.AddField(
            model_name="lemmatization",
            name="is_plural",
            field=models.BooleanField(default=0, help_text="If the text is plural"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="GermanVerb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Any useful comments to keep for internal purposes.",
                        null=True,
                    ),
                ),
                ("base_form", models.CharField(max_length=255, unique=True)),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GermanNoun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Any useful comments to keep for internal purposes.",
                        null=True,
                    ),
                ),
                (
                    "base_form",
                    models.CharField(
                        help_text="ie. singular", max_length=255, unique=True
                    ),
                ),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GermanAdjective",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Any useful comments to keep for internal purposes.",
                        null=True,
                    ),
                ),
                (
                    "base_form",
                    models.CharField(
                        help_text="ie. absolute", max_length=255, unique=True
                    ),
                ),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
