# Generated by Django 4.2.7 on 2023-11-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0040_lemmatization_is_plural_germanverb_germannoun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="englishadjective",
            name="is_absolute",
            field=models.BooleanField(
                default=0, help_text="If adjective is in an absolute"
            ),
            preserve_default=False,
        ),
    ]
