# Generated by Django 4.2.7 on 2023-11-07 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0041_englishadjective_is_absolute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diversitydimension",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="diversitydimension",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="diversitydimension",
            name="order",
        ),
    ]
