# Generated by Django 4.2.7 on 2023-11-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0042_alter_diversitydimension_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rule",
            name="rules_rule_first_t_9fb687_idx",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="first_word_type",
        ),
        migrations.AddField(
            model_name="rule",
            name="lemma_length",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="alternative",
            index=models.Index(
                fields=[
                    "is_active",
                    "rule_id",
                    "is_placeholder",
                    "is_inspiration",
                    "pluralization",
                    "order",
                ],
                name="rules_alter_is_acti_671a5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=[
                    "is_active",
                    "language",
                    "type",
                    "first_token",
                    "first_is_word_type_lemmatize",
                    "first_is_word_type_lower_case",
                ],
                name="rules_rule_is_acti_3e9519_idx",
            ),
        ),
    ]
