# Generated by Django 4.2.7 on 2023-11-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0043_remove_rule_rules_rule_first_t_9fb687_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="lemma_length",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
