# Generated by Django 4.2.7 on 2023-11-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0044_alter_rule_lemma_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsentence",
            name="is_on_website",
            field=models.BooleanField(
                default=False, help_text="If sentences is an example on the website"
            ),
        ),
        migrations.AlterField(
            model_name="trainingsentence",
            name="is_false_positive",
            field=models.BooleanField(
                default=False, help_text="If sentences should not trigger the rule"
            ),
        ),
        migrations.AlterField(
            model_name="trainingsentence",
            name="is_training_data",
            field=models.BooleanField(
                default=False,
                help_text="If sentences should be used for the custom machine learning model",
            ),
        ),
    ]
