# Generated by Django 4.2.7 on 2023-11-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0045_trainingsentence_is_on_website_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="Optional pattern to define word types before and after the lemma. Syntax 'l' for the lemma. '*' means zero or many, '+' means once or many.",
                max_length=255,
                null=True,
            ),
        ),
    ]
