# Generated by Django 4.2.7 on 2023-11-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0046_rule_patern"),
    ]

    operations = [
        migrations.AddField(
            model_name="germanverb",
            name="conjunctive_ich",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germanverb",
            name="helping_verb",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germanverb",
            name="imperativ_plural",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germanverb",
            name="imperativ_singular",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germanverb",
            name="infinitiv_zu",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="germanverb",
            name="past_participle",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="germanverb",
            name="past_tense_ich",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germanverb",
            name="present_du",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germanverb",
            name="present_ich",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germanverb",
            name="present_pronoun",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
