# Generated by Django 4.2.7 on 2023-11-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0047_germanverb_conjunctive_ich_germanverb_helping_verb_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="englishadjective",
            name="is_absolute",
            field=models.BooleanField(
                default=False, help_text="If adjective is in an absolute"
            ),
        ),
        migrations.AlterField(
            model_name="lemmatization",
            name="is_plural",
            field=models.BooleanField(default=False, help_text="If the text is plural"),
        ),
    ]
