# Generated by Django 4.2.7 on 2023-11-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0048_alter_englishadjective_is_absolute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="germannoun",
            name="female_form",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="englishnoun",
            name="base_form",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="germanadjective",
            name="base_form",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="germannoun",
            name="base_form",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
