# Generated by Django 4.2.7 on 2023-11-26 14:30

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0049_germannoun_female_form_alter_englishnoun_base_form_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="germannoun",
            name="gender_1",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("neuter", "Neuter"),
                    ("feminine", "Feminine"),
                    ("masculine", "Masculine"),
                ],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="gender_2",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("neuter", "Neuter"),
                    ("feminine", "Feminine"),
                    ("masculine", "Masculine"),
                ],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="pl_dat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="pl_gen",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="pl_nom_acc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="plural_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="sg_dat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="sg_gen",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="sg_nom_acc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="singular_only",
            field=models.BooleanField(default=False),
        ),
    ]
