# Generated by Django 4.2.7 on 2023-11-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0050_germannoun_gender_1_germannoun_gender_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="germanadjective",
            name="comparative",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germanadjective",
            name="is_absolute",
            field=models.BooleanField(
                default=False, help_text="If adjective is in an absolute"
            ),
        ),
        migrations.AddField(
            model_name="germanadjective",
            name="superlative",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="englishadjective",
            name="base_form",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
