# Generated by Django 4.2.7 on 2023-11-27 12:58

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0051_germanadjective_comparative_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="entity_type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("default", "Default"),
                    ("name", "Name"),
                    ("non_name", "Non Name"),
                    ("person", "Person"),
                    ("non_person", "Non Person"),
                    ("number", "Number"),
                    ("datetime", "Datetime"),
                ],
                default="default",
                help_text="If the rule should only match on a specific entity type (name, non_name, person, non_person, number, datetime).",
                max_length=10,
            ),
        ),
    ]
