# Generated by Django 4.2.7 on 2023-11-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0052_rule_entity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="germannoun",
            name="male_form",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
