# Generated by Django 4.2.7 on 2023-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0053_germannoun_male_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternative",
            name="is_advanced",
            field=models.BooleanField(
                default=False,
                help_text="Only show if user has diversity dimension enabled at advanced level.",
            ),
        ),
    ]
