# Generated by Django 4.2.7 on 2023-11-29 17:33

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0054_alter_alternative_is_advanced"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="pluralization",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("default", "Default"),
                    ("singular_only", "Singular Only"),
                    ("plural_only", "Plural Only"),
                ],
                default="default",
                help_text="Show alternative in case rule triggered on singular/plural/both",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="pluralization",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("default", "Default"),
                    ("singular_only", "Singular Only"),
                    ("plural_only", "Plural Only"),
                ],
                default="default",
                help_text="Show alternative in case rule triggered on singular/plural/both",
                max_length=13,
            ),
        ),
    ]
