# Generated by Django 4.2.7 on 2023-11-30 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0055_rule_pluralization_alter_alternative_pluralization"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rule",
            unique_together={
                ("language", "lemma", "word_types", "type", "pluralization")
            },
        ),
    ]
