# Generated by Django 4.2.7 on 2023-12-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0056_alter_rule_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="germannoun",
            old_name="pl_nom_acc",
            new_name="pl_acc",
        ),
        migrations.RenameField(
            model_name="germannoun",
            old_name="sg_nom_acc",
            new_name="pl_nom",
        ),
        migrations.AddField(
            model_name="germannoun",
            name="pl_dat_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="pl_gen_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="sg_acc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="sg_dat_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="sg_gen_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="sg_nom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
