# Generated by Django 4.2.7 on 2023-12-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0057_rename_pl_nom_acc_germannoun_pl_acc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternative",
            name="sanctions",
            field=models.ManyToManyField(
                blank=True, related_name="alternative_sanctions", to="rules.source"
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="sanctions",
            field=models.ManyToManyField(
                blank=True, related_name="rule_sanctions", to="rules.source"
            ),
        ),
    ]
