# Generated by Django 4.2.7 on 2023-12-04 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0058_alternative_sanctions_rule_sanctions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="germannoun",
            name="pl_dat_2",
        ),
        migrations.RemoveField(
            model_name="germannoun",
            name="pl_gen_2",
        ),
    ]
