# Generated by Django 4.2.7 on 2023-12-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0059_remove_germannoun_pl_dat_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternative",
            name="is_collective_noun",
            field=models.BooleanField(
                default=False,
                help_text="If this is a collective noun, which means do not pluralize.",
            ),
        ),
    ]
