# Generated by Django 4.2.7 on 2023-12-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0060_alternative_is_collective_noun"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsentence",
            name="alternative_on_website",
            field=models.CharField(
                default="",
                help_text="Sentences is an example on the website with the following example",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingsentence",
            name="is_on_website",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
