# Generated by Django 4.2.7 on 2023-12-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0061_trainingsentence_alternative_on_website_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsentence",
            name="alternative_on_website",
            field=models.CharField(
                blank=True,
                help_text="Sentences is an example on the website with the following example",
                max_length=255,
            ),
        ),
    ]
