# Generated by Django 4.2.7 on 2023-12-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0062_alter_trainingsentence_alternative_on_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="is_pattern_match",
            field=models.BooleanField(
                default=False,
                help_text="if the pattern should expand the matched text or if it is just used to avoid false positives",
            ),
        ),
    ]
