# Generated by Django 4.2.7 on 2023-12-19 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0063_rule_is_pattern_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="rules.rule",
            ),
        ),
    ]
