# Generated by Django 4.2.8 on 2023-12-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0064_rule_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="links",
            field=models.ManyToManyField(blank=True, to="rules.rule"),
        ),
    ]
