# Generated by Django 4.2.8 on 2024-01-04 08:50

from django.db import migrations, models
import django_enum.fields
import requests
from rules.models import fetch_json

import logging


def get_console_logger():
    logger = logging.getLogger(__name__)
    handler = logging.StreamHandler()
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)

    logger.info("starting logger")
    return logger

def forwards_func(apps, schema_editor):
    rule_model = apps.get_model("rules", "Rule")
    db_alias = schema_editor.connection.alias
    rules = rule_model.objects.using(db_alias).all()
    for rule in rules:
        if rule.word_types is None or len(rule.word_types) == 0:
            continue

        word_types = rule.word_types.split("|")
        word_type = ''.join(ch for ch in word_types[0] if ch.isalpha())
        rule.first_word_type = word_type
        rule.save()


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0065_rule_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="first_word_type",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="germannoun",
            name="gender_1",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("neuter", "Neuter"),
                    ("feminine", "Feminine"),
                    ("masculine", "Masculine"),
                ],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="germannoun",
            name="gender_2",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("neuter", "Neuter"),
                    ("feminine", "Feminine"),
                    ("masculine", "Masculine"),
                ],
                max_length=9,
                null=True,
            ),
        ),
    ]
