# Generated by Django 4.2.8 on 2024-01-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0066_rule_first_word_type_alter_germannoun_gender_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diversitydimension",
            name="has_de_rules",
            field=models.BooleanField(
                default=False, help_text="If the diversity dimension has German rules"
            ),
        ),
        migrations.AddField(
            model_name="diversitydimension",
            name="has_en_rules",
            field=models.BooleanField(
                default=False, help_text="If the diversity dimension has English rules"
            ),
        ),
    ]
