# Generated by Django 4.2.8 on 2024-01-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0067_diversitydimension_has_de_rules_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diversitydimension",
            name="url_de",
            field=models.CharField(
                blank=True,
                help_text="URL to the category page in German",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="diversitydimension",
            name="url_en",
            field=models.CharField(
                blank=True,
                help_text="URL to the category page in English",
                max_length=255,
                null=True,
            ),
        ),
    ]
