# Generated by Django 4.2.8 on 2024-01-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0068_diversitydimension_url_de_diversitydimension_url_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="diversitydimension",
            name="has_rules",
            field=models.BooleanField(
                default=True,
                help_text="If the diversity dimension has rules (or if rules are hardcoded or advanced alternatives only)",
            ),
        ),
    ]
