# Generated by Django 4.2.8 on 2024-01-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0069_diversitydimension_has_rules"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainingsentence",
            old_name="alternative_on_website",
            new_name="alternative_expected",
        ),
        migrations.AlterField(
            model_name="trainingsentence",
            name="alternative_expected",
            field=models.CharField(
                blank=True,
                help_text="Alternative expected to be included in the alternative list",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="trainingsentence",
            name="is_on_website",
            field=models.BooleanField(
                default=False, help_text="If the example is shown on the website"
            ),
        ),
    ]
