# Generated by Django 4.2.10 on 2024-02-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rules",
            "0070_rename_alternative_on_website_trainingsentence_alternative_expected_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="englishnoun",
            name="plural_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
