# Generated by Django 4.2.8 on 2024-01-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rules",
            "0071_englishnoun_plural_2",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="alternative",
            name="is_gendered_noun",
            field=models.BooleanField(
                default=False,
                help_text="If this is a alternative contains gendered nouns and non gendered variations should be generated.",
            ),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="collective_noun",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="collective_noun_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
