# Generated by Django 4.2.10 on 2024-02-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0072_alternative_is_gendered_noun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diversitydimension",
            name="external_name",
            field=models.CharField(
                blank=True,
                help_text="Public name of the diversity dimension",
                max_length=255,
                null=True,
            ),
        ),
    ]
