# Generated by Django 4.2.10 on 2024-03-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0073_diversitydimension_external_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="has_failing_training_sentence",
            field=models.BooleanField(
                default=False,
                help_text="If one of the training sentences is not triggering the given rule as expected",
            ),
        ),
    ]
