# Generated by Django 4.2.10 on 2024-03-13 10:06

from django.db import migrations, models
from django.db import connection

import logging


def get_console_logger():
    logger = logging.getLogger(__name__)
    handler = logging.StreamHandler()
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)

    logger.info("starting logger")
    return logger


def forwards_func(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            "UPDATE rules_rule SET is_hr_rule = 1 WHERE rules_rule.id IN (SELECT object_id FROM taggit_taggeditem INNER JOIN taggit_tag ON taggit_taggeditem.tag_id = taggit_tag.id WHERE taggit_tag.name = 'hr' AND taggit_taggeditem.content_type_id = 2)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0074_rule_has_failing_training_sentence"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="is_hr_rule",
            field=models.BooleanField(
                default=False, help_text="If this rule is enabled only for the HR-addon"
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
