# Generated by Django 4.2.11 on 2024-03-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0075_rule_is_hr_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="germannoun",
            name="pl_nom_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
