# Generated by Django 4.2.8 on 2024-04-03 10:19

from django.db import migrations, models
import django.db.models.deletion
import rules.models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0075_alternativeevaluation_rulestructureevaluation_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rule',
            name='rules_rule_is_acti_3e9519_idx',
        ),
        migrations.RemoveField(
            model_name='alternativeevaluation',
            name='alternative',
        ),
        migrations.AddField(
            model_name='alternativeevaluation',
            name='rule',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='alternative_evaluation', serialize=False, to='rules.rule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='generated_at',
            field=models.DateTimeField(blank=True, help_text='When the rule was auto generated', null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='Rule was auto generated', null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='source_rule',
            field=models.CharField(blank=True, help_text='Rule that was used to generate this rule', max_length=1000),
        ),
        migrations.AddField(
            model_name='trainingsentenceevaluation',
            name='rule',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='sentence_evaluation', serialize=False, to='rules.rule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alternativeevaluation',
            name='how_good_is_alternative',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=3, help_text='Rate the quality of the alternative.'),
        ),
        migrations.AlterField(
            model_name='alternativeevaluation',
            name='notes_from_evaluator_alternatives',
            field=models.TextField(blank=True, help_text='Observations or notes from the evaluator.', null=True),
        ),
        migrations.AlterField(
            model_name='rulestructureevaluation',
            name='rule',
            field=models.OneToOneField(default=rules.models.RuleStructureEvaluation.unique_default, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, related_name='evaluation', serialize=False, to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='trainingsentenceevaluation',
            name='training_sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rules.trainingsentence'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['is_auto_generated', 'is_active', 'language', 'type', 'first_token', 'first_is_word_type_lemmatize', 'first_is_word_type_lower_case'], name='rules_rule_is_auto_53ffb0_idx'),
        ),
    ]
