# Generated by Django 4.2.11 on 2024-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0076_germannoun_pl_nom_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="actual_word_types",
            field=models.CharField(
                blank=True,
                help_text="Optional '|' separated list of word types matching the actual word types",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alternative",
            name="word_types",
            field=models.CharField(
                blank=True,
                help_text="'|' separated list of word types used for matching the rule (n, pron, a, adv, v, conj, emoji, num, card, article) and optional modifiers: '=' case sensitive unlemmatized, '~' case insensitive unlemmatize, '-' case sensitive lemmatized",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="word_types",
            field=models.CharField(
                blank=True,
                help_text="'|' separated list of word types used for matching the rule (n, pron, a, adv, v, conj, emoji, num, card, article) and optional modifiers: '=' case sensitive unlemmatized, '~' case insensitive unlemmatize, '-' case sensitive lemmatized",
                max_length=255,
                null=True,
            ),
        ),
    ]
