# Generated by Django 4.2.8 on 2024-03-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0077_rule_actual_word_types_alter_alternative_word_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeEvaluation',
            fields=[
                ('alternative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='evaluation', serialize=False, to='rules.alternative')),
                ('more_inclusive_than_trigger_word', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default='unsure', help_text='Is the alternative more inclusive than the trigger word?', max_length=255)),
                ('same_meaning_as_trigger_word', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default='unsure', help_text='Does the alternative have the same meaning as the trigger word?', max_length=255)),
                ('how_good_is_alternative', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='How good is the alternative?')),
                ('notes_from_evaluator_alternatives', models.TextField(blank=True, help_text='Any interesing observations or notes from the evaluator.', null=True)),
            ],
            options={
                'verbose_name': 'Alternative Evaluation',
                'verbose_name_plural': 'Alternative Evaluations',
            },
        ),
        migrations.CreateModel(
            name='RuleStructureEvaluation',
            fields=[
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='evaluation', serialize=False, to='rules.rule')),
                ('text_id_correctness', models.IntegerField(choices=[(0, "Don't know"), (1, 'Incorrect'), (2, 'Somewhat correct'), (3, 'Correct')], default=0, help_text='Correctness of the text_id field.')),
                ('lemma_correctness', models.IntegerField(choices=[(0, "Don't know"), (1, 'Incorrect'), (2, 'Somewhat correct'), (3, 'Correct')], default=0, help_text='Correctness of the lemma field.')),
                ('word_types_correctness', models.IntegerField(choices=[(0, "Don't know"), (1, 'Incorrect'), (2, 'Somewhat correct'), (3, 'Correct')], default=0, help_text='Correctness of the word_types field.')),
                ('type_correctness', models.IntegerField(choices=[(0, "Don't know"), (1, 'Incorrect'), (2, 'Somewhat correct'), (3, 'Correct')], default=0, help_text='Correctness of the type field.')),
                ('entity_type_correctness', models.IntegerField(choices=[(0, "Don't know"), (1, 'Incorrect'), (2, 'Somewhat correct'), (3, 'Correct')], default=0, help_text='Correctness of the entity_type field.')),
                ('pluralization_correctness', models.IntegerField(choices=[(0, "Don't know"), (1, 'Incorrect'), (2, 'Somewhat correct'), (3, 'Correct')], default=0, help_text='Correctness of the pluralization field.')),
                ('notes_from_evaluator_structure', models.TextField(blank=True, help_text='General notes from the evaluator.', null=True)),
            ],
            options={
                'verbose_name': 'Rule Evaluation',
                'verbose_name_plural': 'Rule Evaluations',
            },
        ),
        migrations.CreateModel(
            name='TrainingSentenceEvaluation',
            fields=[
                ('training_sentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='evaluation', serialize=False, to='rules.trainingsentence')),
                ('gramatically_correct', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default='unsure', help_text='Is the sentence grammatically correct?', max_length=255)),
                ('fits_context', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default='unsure', help_text='Does the sentence make sense in context of the rule?', max_length=255)),
                ('written_by_human', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default='unsure', help_text='Would you believe that the sentence was written by a human?', max_length=255)),
                ('should_trigger_rule', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default='unsure', help_text='Should the sentence trigger the rule?', max_length=255)),
                ('notes_from_evaluator_training_sentences', models.TextField(blank=True, help_text='Any interesing observations or notes from the evaluator.', null=True)),
            ],
            options={
                'verbose_name': 'Training Sentence Evaluation',
                'verbose_name_plural': 'Training Sentence Evaluations',
            },
        ),
    ]
