# Generated by Django 4.2.8 on 2024-04-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0079_remove_rule_rules_rule_is_acti_3e9519_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsentenceevaluation',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='trainingsentenceevaluation',
            name='training_sentence',
        ),
        migrations.RemoveField(
            model_name='rulestructureevaluation',
            name='entity_type_correctness',
        ),
        migrations.RemoveField(
            model_name='rulestructureevaluation',
            name='lemma_correctness',
        ),
        migrations.RemoveField(
            model_name='rulestructureevaluation',
            name='notes_from_evaluator_structure',
        ),
        migrations.RemoveField(
            model_name='rulestructureevaluation',
            name='pluralization_correctness',
        ),
        migrations.RemoveField(
            model_name='rulestructureevaluation',
            name='text_id_correctness',
        ),
        migrations.RemoveField(
            model_name='rulestructureevaluation',
            name='type_correctness',
        ),
        migrations.RemoveField(
            model_name='rulestructureevaluation',
            name='word_types_correctness',
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='alternative_1_inclusiveness',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'unsure'), (3, 'not applicable')], default=0, help_text='Is alternative 1 more inclusive than rule trigger'),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='alternative_1_quality',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent'), (6, 'Not applicable')], default=3, help_text='Rate the quality of alternative 1'),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='alternative_2_inclusiveness',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'unsure'), (3, 'not applicable')], default=0, help_text='Is alternative 2 m0re inclusive than rule trigger'),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='alternative_2_quality',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent'), (6, 'Not applicable')], default=3, help_text='Rate the quality of alternative 2'),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='alternative_3_inclusiveness',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'unsure'), (3, 'not applicable')], default=0, help_text='Is alternative 3 more inclusive than rule trigger'),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='alternative_3_quality',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent'), (6, 'Not applicable')], default=3, help_text='Rate the quality of alternative 3'),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='alternative_notes',
            field=models.TextField(blank=True, help_text='Interesting notes/observations on alternatives', null=True),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='notes_training_sentences',
            field=models.TextField(blank=True, help_text='Interesting notes/observations on training sentences', null=True),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='rule_carries_same_meaning',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'unsure')], default=0, help_text='Does this rule carry the same meaning as the source rule? '),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='rule_fits_diversity_dimension',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'unsure')], default=0, help_text='Does this rule fit the diversity dimension? '),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='rule_importance',
            field=models.IntegerField(choices=[(1, 'not important'), (2, 'less important'), (3, 'important'), (4, 'very important'), (5, 'extremely important')], default=3, help_text='How important is it that we have this rule?'),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='rule_inclusiveness',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'unsure')], default=0, help_text='Is this rule trigger uninclusive'),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='rule_inspiration',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no')], default=1, help_text='Does this rule inspire the creation of another rule (if yes, write it in notes)?'),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='rule_notes',
            field=models.TextField(blank=True, help_text='Interesting notes/observations on rule', null=True),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='rule_source_rule',
            field=models.CharField(blank=True, help_text='Rule that was used to generate this rule', max_length=5000),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='training_sentence_1_fits_context',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure'), ('not applicable', 'Not Applicable')], default='unsure', help_text='Does training sentence 1 make sense in context of the rule?', max_length=255),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='training_sentence_2_fits_context',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure'), ('not applicable', 'Not Applicable')], default='unsure', help_text='Does training sentence 2 make sense in context of the rule?', max_length=255),
        ),
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='written_by_human',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], default='unsure', help_text='Would you believe that the sentences were written by a human?', max_length=255),
        ),
        migrations.DeleteModel(
            name='AlternativeEvaluation',
        ),
        migrations.DeleteModel(
            name='TrainingSentenceEvaluation',
        ),
    ]
