# Generated by Django 4.2.11 on 2024-04-19 09:26

from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0080_remove_trainingsentenceevaluation_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulestructureevaluation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alternative',
            name='language',
            field=django_enum.fields.EnumCharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], default='en', editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='lemmatization',
            name='language',
            field=django_enum.fields.EnumCharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='rule',
            name='language',
            field=django_enum.fields.EnumCharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='rulestructureevaluation',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='rules.rule'),
        ),
    ]
