# Generated by Django 4.2.11 on 2024-04-23 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rules", "0081_rulestructureevaluation_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rulestructureevaluation",
            name="createdby",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rulestructureevaluation",
            name="id",
            field=models.AutoField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
