# Generated by Django 4.2.11 on 2024-04-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0082_rulestructureevaluation_createdby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="germanverb",
            name="conjunctive_ich",
            field=models.CharField(
                blank=True, help_text="Konjunktiv II Ich", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="germanverb",
            name="helping_verb",
            field=models.CharField(
                blank=True, help_text="Hilfsverb", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="germanverb",
            name="imperativ_plural",
            field=models.CharField(
                blank=True, help_text="Imperative Plural", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="germanverb",
            name="imperativ_singular",
            field=models.CharField(
                blank=True, help_text="Imperative Singular", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="germanverb",
            name="infinitiv_zu",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Infinitiv Zu",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="germanverb",
            name="past_participle",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Past Perfekt",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="germanverb",
            name="past_tense_ich",
            field=models.CharField(
                blank=True, help_text="Past Ich", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="germanverb",
            name="present_du",
            field=models.CharField(
                blank=True, help_text="Present Du", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="germanverb",
            name="present_ich",
            field=models.CharField(
                blank=True, help_text="Present Ich", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="germanverb",
            name="present_pronoun",
            field=models.CharField(
                blank=True, help_text="Present Er/Sie", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rulestructureevaluation",
            name="rule_source_rule",
            field=models.TextField(
                blank=True,
                help_text="Rule that was used to generate this rule",
                null=True,
            ),
        ),
    ]
