# Generated by Django 4.2.11 on 2024-05-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0083_alter_germanverb_conjunctive_ich_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="rule_translation_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rules.rule",
            ),
        ),
    ]
