# Generated by Django 4.2.11 on 2024-05-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0084_rule_rule_translation_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="source_rule",
            field=models.CharField(
                blank=True,
                help_text="Rule that was used to generate this rule",
                max_length=2000,
            ),
        ),
    ]
