# Generated by Django 4.2.11 on 2024-05-27 06:59

from django.db import migrations
from django.db import connection
import django_enum.fields


def forwards_func(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            "UPDATE rules_germannoun SET ner = 'person' WHERE female_form IS NOT NULL OR male_form IS NOT NULL"
        )

        cursor.execute(
            "UPDATE rules_germannoun AS rgn SET ner = 'person' WHERE EXISTS (SELECT * FROM rules_germannoun AS rgn2 WHERE rgn.base_form = rgn2.collective_noun) or EXISTS (SELECT * FROM rules_germannoun AS rgn2 WHERE rgn.base_form = rgn2.collective_noun_2)"
        )

        cursor.execute(
            "UPDATE rules_englishnoun SET ner = 'person' WHERE base_form = 'employee' OR base_form = 'colleague' OR base_form = 'person'"
        )

        cursor.execute(
            "UPDATE rules_englishnoun SET ner = 'group' WHERE base_form = 'team'"
        )

        params = [
            "nicht auf Menschen beziehen",
            "nicht für Einzelperson",
            "nicht für Personen verwenden",
            "Don''t use this word to describe a person",
            "Don''t use this word for people",
            "Try not to use this word to describe people",
            "Try not to use this word to describe people or interactions",
        ]
        cursor.execute(
            f"UPDATE rules_rule SET label = NULL, label_type = 'not_for_people' WHERE label IN ('{params[0]}', '{params[1]}', '{params[2]}', '{params[3]}', '{params[4]}', '{params[5]}', '{params[6]}')",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0085_alter_rule_source_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="englishnoun",
            name="ner",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("neuter", "Person"),
                    ("feminine", "Organization"),
                    ("location", "Location"),
                    ("thing", "Thing"),
                    ("misc", "Misc"),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="germannoun",
            name="ner",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("neuter", "Person"),
                    ("feminine", "Organization"),
                    ("location", "Location"),
                    ("thing", "Thing"),
                    ("misc", "Misc"),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
