# Generated by Django 4.2.13 on 2024-06-18 13:49

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0086_englishnoun_ner_germannoun_ner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="englishnoun",
            name="ner",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("person", "Person"),
                    ("group", "Group"),
                    ("organization", "Organization"),
                    ("location", "Location"),
                    ("thing", "Thing"),
                    ("misc", "Misc"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="germannoun",
            name="ner",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("person", "Person"),
                    ("group", "Group"),
                    ("organization", "Organization"),
                    ("location", "Location"),
                    ("thing", "Thing"),
                    ("misc", "Misc"),
                ],
                max_length=12,
                null=True,
            ),
        ),
    ]
