# Generated by Django 4.2.13 on 2024-06-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0087_alter_englishnoun_ner_alter_germannoun_ner"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rule",
            unique_together={
                ("language", "lemma", "word_types", "type", "pluralization", "pattern")
            },
        ),
    ]
