# Generated by Django 5.0.6 on 2024-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0088_alter_rule_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="is_not_translatable",
            field=models.BooleanField(
                default=False,
                help_text="If this rule cannot be translated from the source language",
            ),
        ),
    ]
