# Generated by Django 5.0.6 on 2024-07-04 08:50

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0089_rule_is_not_translatable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="is_not_translatable",
        ),
        migrations.AddField(
            model_name="rule",
            name="is_translatable",
            field=django_enum.fields.EnumCharField(
                choices=[("yes", "Yes"), ("no", "No"), ("unclear", "Unclear")],
                default="yes",
                help_text="If the rule is translatable from the source language",
                max_length=7,
            ),
        ),
    ]
