# Generated by Django 5.0.6 on 2024-07-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0090_remove_rule_is_not_translatable_rule_is_translatable"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleReview",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("rules.rule",),
        ),
    ]
