# Generated by Django 5.1 on 2024-08-28 06:17

from django.db import migrations, models
from django.db import connection


def forwards_func(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            "UPDATE rules_diversitydimension SET has_fr_rules = has_de_rules, url_fr = replace(url_en, '/en/', '/fr/')"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0091_rulereview"),
    ]

    operations = [
        migrations.AddField(
            model_name="diversitydimension",
            name="has_fr_rules",
            field=models.BooleanField(
                default=False, help_text="If the diversity dimension has French rules"
            ),
        ),
        migrations.AddField(
            model_name="diversitydimension",
            name="url_fr",
            field=models.CharField(
                blank=True,
                help_text="URL to the category page in French",
                max_length=255,
                null=True,
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
