# Generated by Django 5.1 on 2024-09-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0092_diversitydimension_has_fr_rules_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="citation",
            field=models.TextField(
                blank=True,
                help_text="How the source should be cited inside clients. May contaoin markdown",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="citation_rendered",
            field=models.TextField(null=True),
        ),
    ]
