# Generated by Django 5.1 on 2024-09-04 07:22

import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0093_source_citation_source_citation_rendered"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="is_citation_shown",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="source",
            name="citation",
            field=markdownfield.models.MarkdownField(
                blank=True,
                help_text="How the source should be cited inside clients. May contain markdown",
                null=True,
                rendered_field="citation_rendered",
                use_editor=False,
            ),
        ),
    ]
