# Generated by Django 5.1 on 2024-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0094_source_is_citation_shown_alter_source_citation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="citation_rendered",
        ),
        migrations.AlterField(
            model_name="source",
            name="citation",
            field=models.TextField(
                blank=True,
                help_text="How the source should be cited inside clients.",
                null=True,
            ),
        ),
    ]
