# Generated by Django 5.1.1 on 2024-10-11 07:50

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0095_remove_source_citation_rendered_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="englishnoun",
            name="ner",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("person", "Person"),
                    ("group", "Group"),
                    ("organization", "Organization"),
                    ("location", "Location"),
                    ("thing", "Thing"),
                    ("misc", "Misc"),
                    ("animal", "Animal"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="germannoun",
            name="ner",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("person", "Person"),
                    ("group", "Group"),
                    ("organization", "Organization"),
                    ("location", "Location"),
                    ("thing", "Thing"),
                    ("misc", "Misc"),
                    ("animal", "Animal"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="alternative",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type__in", ["default", "person_first", "identity_first"])
                ),
                name="rules_Alternative_type_AlternativeTypeEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="alternative",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pluralization__in", ["default", "singular_only", "plural_only"])
                ),
                name="rules_Alternative_pluralization_PluralizationEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="alternative",
            constraint=models.CheckConstraint(
                condition=models.Q(("language__in", ["en", "de", "fr"])),
                name="rules_Alternative_language_LanguageEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="englishnoun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "ner__in",
                        [
                            "",
                            "person",
                            "group",
                            "organization",
                            "location",
                            "thing",
                            "misc",
                            "animal",
                        ],
                    ),
                    ("ner__isnull", True),
                    _connector="OR",
                ),
                name="rules_EnglishNoun_ner_NerTypeEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="germannoun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gender_1__in", ["", "neuter", "feminine", "masculine"]),
                    ("gender_1__isnull", True),
                    _connector="OR",
                ),
                name="rules_GermanNoun_gender_1_GenderTypeEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="germannoun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gender_2__in", ["", "neuter", "feminine", "masculine"]),
                    ("gender_2__isnull", True),
                    _connector="OR",
                ),
                name="rules_GermanNoun_gender_2_GenderTypeEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="germannoun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "ner__in",
                        [
                            "",
                            "person",
                            "group",
                            "organization",
                            "location",
                            "thing",
                            "misc",
                            "animal",
                        ],
                    ),
                    ("ner__isnull", True),
                    _connector="OR",
                ),
                name="rules_GermanNoun_ner_NerTypeEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="lemmatization",
            constraint=models.CheckConstraint(
                condition=models.Q(("language__in", ["en", "de", "fr"])),
                name="rules_Lemmatization_language_LanguageEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="rule",
            constraint=models.CheckConstraint(
                condition=models.Q(("language__in", ["en", "de", "fr"])),
                name="rules_Rule_language_LanguageEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="rule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type__in", ["default", "prefix", "suffix", "substring"])
                ),
                name="rules_Rule_type_RuleTypeEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="rule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "entity_type__in",
                        [
                            "default",
                            "name",
                            "non_name",
                            "person",
                            "non_person",
                            "number",
                            "datetime",
                        ],
                    )
                ),
                name="rules_Rule_entity_type_EntityTypeEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="rule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "label_type__in",
                        [
                            "default",
                            "not_for_people",
                            "be_specific",
                            "name_disability",
                            "only_if_gender_identity_relevant",
                            "not_for_non_combat",
                            "ask_for_preference",
                            "ask_about_traditions",
                            "only_when_referencing_religious_practice",
                            "dont_use_for_substance_use",
                            "dont_use_to_describe_quality",
                            "use_in_tech_only",
                        ],
                    )
                ),
                name="rules_Rule_label_type_RuleLabelEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="rule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pluralization__in", ["default", "singular_only", "plural_only"])
                ),
                name="rules_Rule_pluralization_PluralizationEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="rule",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_translatable__in", ["yes", "no", "unclear"])),
                name="rules_Rule_is_translatable_TranslatableEnum",
            ),
        ),
    ]
