# Generated by Django 5.1.1 on 2024-10-11 14:56

import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
import rules.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0096_alter_englishnoun_ner_alter_germannoun_ner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FrenchNoun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    rules.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Any useful comments to keep for internal purposes.",
                        null=True,
                    ),
                ),
                ("base_form", models.CharField(max_length=255, unique=True)),
                (
                    "female_form",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("male_form", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gender_1",
                    django_enum.fields.EnumCharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("neuter", "Neuter"),
                            ("feminine", "Feminine"),
                            ("masculine", "Masculine"),
                        ],
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "gender_2",
                    django_enum.fields.EnumCharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("neuter", "Neuter"),
                            ("feminine", "Feminine"),
                            ("masculine", "Masculine"),
                        ],
                        max_length=9,
                        null=True,
                    ),
                ),
                ("singular_only", models.BooleanField(default=False)),
                ("plural_only", models.BooleanField(default=False)),
                ("plural", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "collective_noun",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "collective_noun_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ner",
                    django_enum.fields.EnumCharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("person", "Person"),
                            ("group", "Group"),
                            ("organization", "Organization"),
                            ("location", "Location"),
                            ("thing", "Thing"),
                            ("misc", "Misc"),
                            ("animal", "Animal"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "createdby",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("gender_1__in", ["", "neuter", "feminine", "masculine"]),
                            ("gender_1__isnull", True),
                            _connector="OR",
                        ),
                        name="rules_FrenchNoun_gender_1_GenderTypeEnum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("gender_2__in", ["", "neuter", "feminine", "masculine"]),
                            ("gender_2__isnull", True),
                            _connector="OR",
                        ),
                        name="rules_FrenchNoun_gender_2_GenderTypeEnum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "ner__in",
                                [
                                    "",
                                    "person",
                                    "group",
                                    "organization",
                                    "location",
                                    "thing",
                                    "misc",
                                    "animal",
                                ],
                            ),
                            ("ner__isnull", True),
                            _connector="OR",
                        ),
                        name="rules_FrenchNoun_ner_NerTypeEnum",
                    ),
                ],
            },
        ),
    ]
