# Generated by Django 5.1.2 on 2024-10-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0097_frenchnoun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="rules.rule",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="rule_translation_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rules.rule",
            ),
        ),
    ]
