# Generated by Django 5.1.3 on 2024-11-27 16:04

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0098_alter_rule_parent_alter_rule_rule_translation_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lemmatization",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="lemmatization",
            name="word_type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("", "None"),
                    ("n", "noun"),
                    ("v", "verb"),
                    ("a", "adjective"),
                ],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lemmatization",
            unique_together={("language", "text", "word_type")},
        ),
        migrations.AddConstraint(
            model_name="lemmatization",
            constraint=models.CheckConstraint(
                condition=models.Q(("word_type__in", ["", "n", "v", "a"])),
                name="rules_Lemmatization_word_type_WordTypeEnum",
            ),
        ),
    ]
