# Generated by Django 5.2.16 on 2026-08-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0099_alter_lemmatization_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("nlp_api_url", models.CharField(max_length=255)),
                (
                    "api_app_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "api_git_revision",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "spacy_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "model_versions",
                    models.JSONField(
                        default=dict,
                        help_text="Per-language spaCy model name and version",
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="RuleEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "failing",
                    models.BooleanField(
                        help_text="A positive training sentence did not trigger the rule"
                    ),
                ),
                (
                    "previous_flag",
                    models.BooleanField(
                        help_text="Value of has_failing_training_sentence when this run started"
                    ),
                ),
                ("sentence_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_check_evaluations",
                        to="rules.rule",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_evaluations",
                        to="rules.evaluationrun",
                    ),
                ),
            ],
            options={
                "unique_together": {("run", "rule")},
            },
        ),
        migrations.CreateModel(
            name="TrainingSentenceEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched", models.BooleanField(null=True)),
                ("passed", models.BooleanField(null=True)),
                ("is_false_positive", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_evaluations",
                        to="rules.rule",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_evaluations",
                        to="rules.evaluationrun",
                    ),
                ),
                (
                    "training_sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="rules.trainingsentence",
                    ),
                ),
            ],
            options={
                "unique_together": {("run", "training_sentence")},
            },
        ),
    ]
